### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by juslintek** [pbrilius/docker-solution-alna#3]
The project works overall.

But UI is lacking better UX.

There is no progress monitoring,
- It is hard to distinguish the general area from the input field.
- It is hard to distinguish the button from the label or it doesn't act as a clickable interactable item.

Everything else is fine.

As well wanted project to be as two separate projects as initially, the problem at that point was missing CORS header that would allow from server frontend requests, domains must match or header must contain the matching domain, like for example:
- Access-Control-Allow-Origin: * // allows all
- Access-Control-Allow-Origin: https://localhost:3000 // allows only the localhost from port 3000
- Access-Control-Allow-Origin: /some-regex/ //allows any target API URL that matches regex.

Regarding https://github.com/pbrilius/frontend-alna this should've only contained vue-js project initiated via vuecli. And for UI could've used https://v3.vuejs.org/examples/todomvc.html example :-)

Wait for HR to contact.

**Comment by pbrilius** [comment]
Would you like it to be arranged differently otherwise 🙂? With Twitter
bootstrap framework UX & UI and 2 Laravel projects as initially suggested?
I can start working on it 😸 tomorrow. API with JSON data payload will be
included by default.

2021-01-22, pn 19:51, Linas <notifications@github.com> rašė:

**Comment by pbrilius** [comment]
I am moving the direction towards re-development of previous solution like _2 LR Docker_ projects based  [Alna project](https://github.com/pbrilius/project-alna) which we discussed earlier @juslintek .

**Comment by juslintek** [comment]
@pbrilius, it is fine; you no longer need to work on it. Just wait for info from HR. :-)

**Comment by pbrilius** [comment]
OK 👌 just in case, check the moved project management, it's launched, called _feedback correction_.
